import type { Metadata } from "next";
import type React from "react";
import { NoirHeader } from "@/components/dealforge/noir-header";

export const metadata: Metadata = {
  title: "Noir",
  description: "Generated by create-solana-dapp",
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <NoirHeader />
      <div className="flex flex-1 flex-col">
        <div className="@container/main flex flex-1 flex-col gap-2">
          <div className="px-6">{children}</div>
        </div>
      </div>
    </>
  );
}
